version: "3.8"

services:
  be:
    container_name: travelife-be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=mysecretpassword
    volumes:
      - redis_data:/data
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt:ro
    ports:
      - "80:80" # HTTP port
      - "443:443" # HTTPS port
    depends_on:
      - be
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
