name: Deploy to EC2

on:
  push:
    branches:
      - prod

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get commit message
        id: get_commit_message
        outputs:
          commit_message: ${{ steps.get_commit_message.outputs.commit_message }}
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "commit_message=$commit_message" >> $GITHUB_OUTPUT

      - name: Deploy to EC2
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          ENV_VARS: ${{ secrets.ENV_VARS }}
          ENV_PYTHON_EXPORT: ${{ secrets.ENV_PYTHON_EXPORT }}
          ENV_NOTIFICATION_WORKER: ${{ secrets.ENV_NOTIFICATION_WORKER }}
          CLIENT_URL: https://travelife-booking.vercel.app
          COMMIT_MSG: ${{ steps.get_commit_message.outputs.commit_message }}
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << EOF
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker network inspect travelife-network >/dev/null 2>&1 || docker network create travelife-network

          COMMIT_MSG="${{ env.COMMIT_MSG }}"

          if echo "$COMMIT_MSG" | grep -q "build:travelife-be"; then
            docker pull $DOCKER_USERNAME/travelife-be:latest
            docker stop travelife-be || true && docker rm travelife-be || true
            echo "$ENV_VARS" > /tmp/travelife.env
            docker run -d --name travelife-be --network travelife-network --env-file /tmp/travelife.env -e CLIENT_URL=$CLIENT_URL -p 4001:4001 $DOCKER_USERNAME/travelife-be:latest
          fi

          if echo "$COMMIT_MSG" | grep -q "build:python-export"; then
            docker pull $DOCKER_USERNAME/python-export:latest
            docker stop python-export || true && docker rm python-export || true
            echo "$ENV_PYTHON_EXPORT" > /tmp/python-export.env
            docker run -d --name python-export --network travelife-network --env-file /tmp/python-export.env -p 5000:5000 $DOCKER_USERNAME/python-export:latest
          fi

          if echo "$COMMIT_MSG" | grep -q "build:notification-worker"; then
            docker pull $DOCKER_USERNAME/notification-worker:latest
            docker stop notification-worker || true && docker rm notification-worker || true
            echo "$ENV_NOTIFICATION_WORKER" | base64 -d > /tmp/config.production.json
            docker run -d --name notification-worker --network travelife-network -v /tmp/config.production.json:/config/config.production.json -p 5002:5002 $DOCKER_USERNAME/notification-worker:latest
          fi

          docker system prune -f
          EOF
